CREATE DATABASE IF NOT EXISTS dragon_university
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE dragon_university;

CREATE TABLE IF NOT EXISTS majors (
  major_id INT PRIMARY KEY AUTO_INCREMENT,
  major_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS classes (
  class_id INT PRIMARY KEY,
  class_code VARCHAR(30) NOT NULL UNIQUE,
  class_name VARCHAR(120) NOT NULL,
  class_desc TEXT NOT NULL,
  seats INT NOT NULL,
  credits INT NOT NULL DEFAULT 3,
  category VARCHAR(60) NOT NULL,
  instructor VARCHAR(60) NOT NULL,
  major_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (major_id) REFERENCES majors(major_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS students (
  stu_id INT PRIMARY KEY AUTO_INCREMENT,
  stu_name VARCHAR(50) NOT NULL,
  stu_num VARCHAR(20) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(120),
  max_classes INT NOT NULL DEFAULT 3,
  max_credits INT NOT NULL DEFAULT 18,
  major_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (major_id) REFERENCES majors(major_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS stu_classes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  stu_id INT NOT NULL,
  class_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_student_class (stu_id, class_id),
  FOREIGN KEY (stu_id) REFERENCES students(stu_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (class_id) REFERENCES classes(class_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS admins (
  id INT PRIMARY KEY AUTO_INCREMENT,
  admin_user VARCHAR(50) UNIQUE NOT NULL,
  admin_pass VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
